// Explicit user-profile schema exports keep public protocol changes reviewable.
export {
  GIT_COAUTHOR_PREFERENCE_KEY,
  isGitCoauthorCreditEnabled,
  normalizeUiAppearancePreference,
  UI_APPEARANCE_PREFERENCE_KEYS,
  UserProfileAuthLinkSchema,
  UsersAuthConnectCompleteParamsSchema,
  UsersAuthConnectResultSchema,
  UsersAuthConnectStartParamsSchema,
  UsersAuthConnectStartResultSchema,
  UsersAuthConnectTokenParamsSchema,
  UserProfileSchema,
  UsersLinkAuthProfileParamsSchema,
  UsersLinkAuthProfileResultSchema,
  UsersLinkEmailParamsSchema,
  UsersLinkEmailResultSchema,
  UsersListAuthLinksParamsSchema,
  UsersListAuthLinksResultSchema,
  UsersListParamsSchema,
  UsersListResultSchema,
  UsersPrefsGetParamsSchema,
  UsersPrefsGetResultSchema,
  UsersPrefsChangedEventSchema,
  UsersPrefsSetParamsSchema,
  UsersPrefsSetResultSchema,
  UsersSelfParamsSchema,
  UsersSelfResultSchema,
  UsersSetAvatarParamsSchema,
  UsersSetAvatarResultSchema,
  UsersSetDisplayNameParamsSchema,
  UsersSetDisplayNameResultSchema,
  UsersSetRoleParamsSchema,
  UsersSetRoleResultSchema,
  UsersUnlinkAuthProfileParamsSchema,
  UsersUnlinkAuthProfileResultSchema,
} from "./schema-modules.js";
